### ISSUE TITLE
Test development environment on Linux/Windows/MacOS

### ISSUE THREAD

**Issue by the-teacher** [TheRole/the_role_dev#1]
We need to check if these steps of the Readme are correct and work.

Just do things step by step and check if everything works well.

<img width="744" alt="Screenshot 2023-07-02 at 15 20 54" src="https://github.com/TheRole/the_role_dev/assets/496713/880a0af6-02a3-4e67-95ae-c7ee040e84da">

**Comment by o-200** [comment]
That step-guide is correct. Initialization works without any errors. Linux

**Comment by seuros** [comment]
I will edit it to use submodules to we can remove the setup phase.

Also it better if we ditch rails 6.

**Comment by sk8higher** [comment]
Guide is correct, works on Linux without errors, tests pass

![image](https://github.com/TheRole/the_role_dev/assets/30351533/01b87f2e-ef48-4a91-b1ba-a258de05e41f)

**Comment by sk8higher** [comment]
Works also on Ubuntu WSL2, Windows, without errors (Ruby 3.2.2, asdf in WSL)

**Comment by Alex808r** [comment]
MacOs Monterey, work without `nvm install 18.12.1`

<img width="1488" alt="Снимок экрана 2023-07-04 в 18 10 20" src="https://github.com/TheRole/the_role_dev/assets/78639180/db4f9544-9fdd-4315-8275-076e9380029b">

upd:
works!

**Comment by ekatebenkova** [comment]
On Windows 11 works without errors (Ruby 3.1.2, docker 24.0.2)

![image](https://github.com/TheRole/the_role_dev/assets/50392575/79e424ac-c297-41fb-b749-d97b07fad662)

![image](https://github.com/TheRole/the_role_dev/assets/50392575/1db5e25b-cab0-4bf8-9380-d2a5ce670ca2)

**Comment by Pavelandr1207** [comment]
![Test](https://github.com/TheRole/the_role_dev/assets/114385469/8d1bd969-9104-4390-8d6e-0b067d5239cf)
Linux Mint
