### ISSUE TITLE
Add Gemfile.lock files to .gitignore

### ISSUE THREAD

**Issue by o-200** [TheRole/the_role_dev#13]
Every time when we installing project we always update gem versions. 

Git shouldn track these files because they can will updating in every merge

**Comment by the-teacher** [comment]
🤔 I didn't get what a problem here. Usually `.lock` files should be in repo.
Let's have a talk about the topic in private.

**Comment by o-200** [comment]
> thinking I didn't get what a problem here. Usually `.lock` files should be in repo. Let's have a talk about the topic in private.

i've checked rules when adding gemfile.lock in gitignore is a best practise. And this is not our way.

We are using docker and there is no situation when gemfile updates on a different systems. Closed
